### ISSUE TITLE
Sending a colonist removes all health effects.

### ISSUE THREAD

**Issue by Fro-Z** [Longwelwind/Phi#15] opened 2017-02-15 15:13 UTC
Sending a colonist to player removes all health effects of the colonist. Including permanent ones.

**Comment by SapphireMH** [comment] 2017-12-02 20:06
I can confirm that this issue is still in the latest version of the mod.
Rimworld Beta 18
Mod version 0.13

After looking through the code it becomes clear what the cause of the issues is.

In detail:
When the mod sends a colonist it creates a template based on the info it collected from the specified colonist, then on the receiving end a new colonist gets generated using the created template.

The system itself for this works fine, however some extra data (health effects, scars, addictions, bionics, etc.) are currently not included when the template is created, resulting in the receiving player getting a fully healthy colonist instead of one who might have been bleeding or missing a finger.

This could be resolved by adding extra parameters to the code to check for the health data and adding this to the template for generating the new colonist.

**Closed as completed** 2018-06-04 18:28 UTC
